# Site Data
title: Maxime Solaire - Portfolio & Devlog
description: All about my game development challenges, programming insights, and creative projects.
image: /assets/images/default-preview-image.png
url: https://solrmax.github.io
baseurl: ""

# Configuration
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
#google_analytics: G-M7HRV5WG9L
show_downloads: false
show_navigation: true
permalink: /blog/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      category: blog
feed:
  posts_limit: 10
  path: /blog/feed.xml
  icon: /images/favicon/website-icon-32x32.png
  logo: /images/favicon/website-icon-32x32.png


# Profile
author:
  name: Maxime Solaire
  nickname: Layar
  title: Senior Unity Developer & Technical Producer
  description: 10+ years building games from prototype to production—technical development, team leadership, and cross-discipline coordination to ship polished experiences on time.
socials:
  - name: cv
    url: /resume
    inTab: true
  - name: linkedin
    url: https://www.linkedin.com/in/msolaire
  - name: github
    url: https://github.com/solrmax
  - name: itch.io
    url: https://layar.itch.io
support_me:
  name: Buy me a Coffe! ☕︎
  url: https://buymeacoffe.com
  show: false

# Contact
chat_platforms:
    - name: linkedin
      url: https://www.linkedin.com/in/msolaire/
      handler: in/msolaire/
    - name: discord
      handler: maxlayar