remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
title: The Fifth Corner - Portfolio & Devlog
description: Portfolio and personal blog about programming, video games and design!
google_analytics: G-M7HRV5WG9L
show_downloads: false

# Profile
author: 
  name: Esteban Gaete Flores
  title: Senior Unity Game Developer
  description: Gameplay & Tools Engineer with 10+ years creating fast, clean systems, responsive gameplay, and tools that boost team efficiency.
socials:
  - name: cv
    url: https://docs.google.com/document/d/17ror9scPDFVUMK6okj4Yf7gdI_MyANjwWboukXwG8pc/edit?usp=sharing
  - name: linkedin
    url: https://www.linkedin.com/in/estebangaeteflores
  - name: github
    url: https://github.com/Theby