# Site Data
title: The Fifth Corner - Portfolio & Devlog
description: All about my game development challenges, programming insights, and creative projects.
image: /assets/images/default-preview-image.png
url: https://theby.github.io
baseurl: ""

# Configuration
emote_theme: pages-themes/hacker@v0.2.0
plugins:
 - jekyll-remote-theme
  - jekyll-feed
google_analytics: G-M7HRV5WG9L
show_downloads: false
show_navigation: true
permalink: /blog/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      category: blog
feed:
  posts_limit: 10
  path: /blog/feed.xml
  icon: /images/favicon/website-icon-32x32.png
  logo: /images/favicon/website-icon-32x32.png


# Profile
author: 
  name: Esteban Gaete Flores
  title: Senior Unity Game Developer
  description: Gameplay & Tools Engineer with 10+ years creating fast, clean systems, responsive gameplay, and tools that boost team efficiency.
socials:
  - name: cv
    url: /resume
    inTab: true
  - name: linkedin
    url: https://www.linkedin.com/in/estebangaeteflores
  - name: github
    url: https://github.com/Theby

# Contact
chat_platforms:
    - name: x
      url: https://x.com/TebiFestival
      handler: TebiFestival
    - name: bluesky
      url: https://bsky.app/profile/tebisight.bsky.social
      handler: tebisight.bsky.social
    - name: linkedin
      url: https://www.linkedin.com/in/estebangaeteflores/
      handler: in/estebangaeteflores/
    - name: discord
      handler: tebifestival